export const GET_ORGANIZATION_START = "GET_ORGANIZATION_START";
export const GET_ORGANIZATION_SUCCESS = "GET_ORGANIZATION_SUCCESS";
export const GET_ORGANIZATION_FAILURE = "GET_ORGANIZATION_FAILURE";

export const CREATE_ORGANIZATION_START = "GET_ORGANIZATION_START";
export const CREATE_ORGANIZATION_SUCCESS = "GET_ORGANIZATION_SUCCESS";
export const CREATE_ORGANIZATION_FAILURE = "GET_ORGANIZATION_FAILURE";

export const UPDATE_ORGANIZATION_START = "GET_ORGANIZATION_START";
export const UPDATE_ORGANIZATION_SUCCESS = "GET_ORGANIZATION_SUCCESS";
export const UPDATE_ORGANIZATION_FAILURE = "GET_ORGANIZATION_FAILURE";

export const DELETE_ORGANIZATION_START = "GET_ORGANIZATION_START";
export const DELETE_ORGANIZATION_SUCCESS = "GET_ORGANIZATION_SUCCESS";
export const DELETE_ORGANIZATION_FAILURE = "GET_ORGANIZATION_FAILURE";

