//Action types for meetings

export const GET_MEETINGS_START = "GET_MEETINGS_START";
export const GET_MEETINGS_SUCCESS = "GET_MEETINGS_SUCCESS";
export const GET_MEETINGS_FAILURE = "GET_MEETINGS_FAILURE";

export const CREATE_MEETING_START = "CREATE_MEETING_START";
export const CREATE_MEETING_SUCCESS = "CREATE_MEETING_SUCCESS";
export const CREATE_MEETING_FAILURE = "CREATE_MEETING_FAILURE";

export const UPDATE_MEETING_START = "UPDATE_MEETING_START";
export const UPDATE_MEETING_SUCCESS = "UPDATE_MEETING_SUCCESS";
export const UPDATE_MEETING_FAILURE = "UPDATE_MEETING_FAILURE";

export const DELETE_MEETING_START = "DELETE_MEETING_START";
export const DELETE_MEETING_SUCCESS = "DELETE_MEETING_SUCCESS";
export const DELETE_MEETING_FAILURE = "DELETE_MEETING_FAILURE";


//Action types for organizations

export const GET_ORGANIZATION_START = "GET_ORGANIZATION_START";
export const GET_ORGANIZATION_SUCCESS = "GET_ORGANIZATION_SUCCESS";
export const GET_ORGANIZATION_FAILURE = "GET_ORGANIZATION_FAILURE";

export const CREATE_ORGANIZATION_START = "GET_ORGANIZATION_START";
export const CREATE_ORGANIZATION_SUCCESS = "GET_ORGANIZATION_SUCCESS";
export const CREATE_ORGANIZATION_FAILURE = "GET_ORGANIZATION_FAILURE";

export const UPDATE_ORGANIZATION_START = "GET_ORGANIZATION_START";
export const UPDATE_ORGANIZATION_SUCCESS = "GET_ORGANIZATION_SUCCESS";
export const UPDATE_ORGANIZATION_FAILURE = "GET_ORGANIZATION_FAILURE";

export const DELETE_ORGANIZATION_START = "GET_ORGANIZATION_START";
export const DELETE_ORGANIZATION_SUCCESS = "GET_ORGANIZATION_SUCCESS";
export const DELETE_ORGANIZATION_FAILURE = "GET_ORGANIZATION_FAILURE";


//action types for user registration

export const REGISTER_USER_START = "REGISTER_USER_START";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

//action types for user login

export const LOGIN_USER_START = "LOGIN_USER_START";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";


//action types for student to apply to be a mentor

export const GET_STUDENT_INFO_START = "GET_STUDENT_INFO_START";
export const GET_STUDENT_INFO_SUCCESS = "GET_STUDENT_INFO_SUCCESS";
export const GET_STUDENT_INFO_FAILURE = "GET_STUDENT_INFO_FAILURE";
