// AUTH

export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const REGISTER_ORGANIZATION_START = 'REGISTER_ORGANIZATION_START';
export const REGISTER_ORGANIZATION_SUCCESS = 'REGISTER_ORGANIZATION_SUCCESS';
export const REGISTER_ORGANIZATION_FAILURE = 'REGISTER_ORGANIZATION_FAILURE';

export const LOGIN_USER_WITH_GITHUB_START = 'LOGIN_USER_WITH_GITHUB_START';
export const LOGIN_USER_WITH_GITHUB_SUCCESS = 'LOGIN_USER_WITH_GITHUB_SUCCESS';
export const LOGIN_USER_WITH_GITHUB_FAILURE = 'LOGIN_USER_WITH_GITHUB_FAILURE';

export const REGISTER_WITH_INVITATION_START = 'REGISTER_WITH_INVITATION_START';
export const REGISTER_WITH_INVITATION_SUCCESS = 'REGISTER_WITH_INVITATION_SUCCESS';
export const REGISTER_WITH_INVITATION_FAILURE = 'REGISTER_WITH_INVITATION_FAILURE';

export const GITHUB_REGISTER_WITH_INVITATION_START = 'GITHUB_REGISTER_WITH_INVITATION_START';
export const GITHUB_REGISTER_WITH_INVITATION_SUCCESS = 'GITHUB_REGISTER_WITH_INVITATION_SUCCESS';
export const GITHUB_REGISTER_WITH_INVITATION_FAILURE = 'GITHUB_REGISTER_WITH_INVITATION_FAILURE';

export const LOGOUT_USER_START = 'LOGOUT_USER_START';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAILURE = 'LOGOUT_USER_FAILURE';

// EXPERIENCES

export const GET_EXPERIENCES_START = 'GET_EXPERIENCES_START';
export const GET_EXPERIENCES_SUCCESS = 'GET_EXPERIENCES_SUCCESS';
export const GET_EXPERIENCES_FAILURE = 'GET_EXPERIENCES_FAILURE';

export const GET_SPECIFIC_EXPERIENCE_START = 'GET_SPECIFIC_EXPERIENCE_START';
export const GET_SPECIFIC_EXPERIENCE_SUCCESS = 'GET_SPECIFIC_EXPERIENCE_SUCCESS';
export const GET_SPECIFIC_EXPERIENCE_FAILURE = 'GET_SPECIFIC_EXPERIENCE_FAILURE';

export const CREATE_EXPERIENCE_START = 'CREATE_EXPERIENCE_START';
export const CREATE_EXPERIENCE_SUCCESS = 'CREATE_EXPERIENCE_SUCCESS';
export const CREATE_EXPERIENCE_FAILURE = 'CREATE_EXPERIENCE_FAILURE';

export const UPDATE_EXPERIENCE_START = 'UPDATE_EXPERIENCE_START';
export const UPDATE_EXPERIENCE_SUCCESS = 'UPDATE_EXPERIENCE_SUCCESS';
export const UPDATE_EXPERIENCE_FAILURE = 'UPDATE_EXPERIENCE_FAILURE';

export const DELETE_EXPERIENCE_START = 'DELETE_EXPERIENCE_START';
export const DELETE_EXPERIENCE_SUCCESS = 'DELETE_EXPERIENCE_SUCCESS';
export const DELETE_EXPERIENCE_FAILURE = 'DELETE_EXPERIENCE_FAILURE';

export const REMOVE_EXPERIENCE_START = 'REMOVE_EXPERIENCE_START';
export const REMOVE_EXPERIENCE_SUCCESS = 'REMOVE_EXPERIENCE_SUCCESS';
export const REMOVE_EXPERIENCE_FAILURE = 'REMOVE_EXPERIENCE_FAILURE';

// INVITATIONS

export const GET_INVITATIONS_START = 'GET_INVITATIONS_START';
export const GET_INVITATIONS_SUCCESS = 'GET_INVITATIONS_SUCCESS';
export const GET_INVITATIONS_FAILURE = 'GET_INVITATIONS_FAILURE';

export const GET_SPECIFIC_INVITATION_START = 'GET_SPECIFIC_INVITATION_START';
export const GET_SPECIFIC_INVITATION_SUCCESS = 'GET_SPECIFIC_INVITATION_SUCCESS';
export const GET_SPECIFIC_INVITATION_FAILURE = 'GET_SPECIFIC_INVITATION_FAILURE';

export const CREATE_INVITATION_START = 'CREATE_INVITATION_START';
export const CREATE_INVITATION_SUCCESS = 'CREATE_INVITATION_SUCCESS';
export const CREATE_INVITATION_FAILURE = 'CREATE_INVITATION_FAILURE';

export const DELETE_INVITATION_START = 'DELETE_INVITATION_START';
export const DELETE_INVITATION_SUCCESS = 'DELETE_INVITATION_SUCCESS';
export const DELETE_INVITATION_FAILURE = 'DELETE_INVITATION_FAILURE';

export const REMOVE_INVITATION_START = 'REMOVE_INVITATION_START';
export const REMOVE_INVITATION_SUCCESS = 'REMOVE_INVITATION_SUCCESS';
export const REMOVE_INVITATION_FAILURE = 'REMOVE_INVITATION_FAILURE';

// MATCHES

export const GET_MATCHES_START = 'GET_MATCHES_START';
export const GET_MATCHES_SUCCESS = 'GET_MATCHES_SUCCESS';
export const GET_MATCHES_FAILURE = 'GET_MATCHES_FAILURE';

export const GET_SPECIFIC_MATCH_START = 'GET_SPECIFIC_MATCH_START';
export const GET_SPECIFIC_MATCH_SUCCESS = 'GET_SPECIFIC_MATCH_SUCCESS';
export const GET_SPECIFIC_MATCH_FAILURE = 'GET_SPECIFIC_MATCH_FAILURE';

export const CREATE_MATCH_START = 'CREATE_MATCH_START';
export const CREATE_MATCH_SUCCESS = 'CREATE_MATCH_SUCCESS';
export const CREATE_MATCH_FAILURE = 'CREATE_MATCH_FAILURE';

export const UPDATE_MATCH_START = 'UPDATE_MATCH_START';
export const UPDATE_MATCH_SUCCESS = 'UPDATE_MATCH_SUCCESS';
export const UPDATE_MATCH_FAILURE = 'UPDATE_MATCH_FAILURE';

export const DELETE_MATCH_START = 'DELETE_MATCH_START';
export const DELETE_MATCH_SUCCESS = 'DELETE_MATCH_SUCCESS';
export const DELETE_MATCH_FAILURE = 'DELETE_MATCH_FAILURE';

export const REMOVE_MATCH_START = 'REMOVE_MATCH_START';
export const REMOVE_MATCH_SUCCESS = 'REMOVE_MATCH_SUCCESS';
export const REMOVE_MATCH_FAILURE = 'REMOVE_MATCH_FAILURE';

// MEETINGS

export const GET_MEETINGS_START = 'GET_MEETINGS_START';
export const GET_MEETINGS_SUCCESS = 'GET_MEETINGS_SUCCESS';
export const GET_MEETINGS_FAILURE = 'GET_MEETINGS_FAILURE';

export const GET_SPECIFIC_MEETING_START = 'GET_SPECIFIC_MEETING_START';
export const GET_SPECIFIC_MEETING_SUCCESS = 'GET_SPECIFIC_MEETING_SUCCESS';
export const GET_SPECIFIC_MEETING_FAILURE = 'GET_SPECIFIC_MEETING_FAILURE';

export const CREATE_MEETING_START = 'CREATE_MEETING_START';
export const CREATE_MEETING_SUCCESS = 'CREATE_MEETING_SUCCESS';
export const CREATE_MEETING_FAILURE = 'CREATE_MEETING_FAILURE';

export const UPDATE_MEETING_START = 'UPDATE_MEETING_START';
export const UPDATE_MEETING_SUCCESS = 'UPDATE_MEETING_SUCCESS';
export const UPDATE_MEETING_FAILURE = 'UPDATE_MEETING_FAILURE';

export const DELETE_MEETING_START = 'DELETE_MEETING_START';
export const DELETE_MEETING_SUCCESS = 'DELETE_MEETING_SUCCESS';
export const DELETE_MEETING_FAILURE = 'DELETE_MEETING_FAILURE';

export const REMOVE_MEETING_START = 'REMOVE_MEETING_START';
export const REMOVE_MEETING_SUCCESS = 'REMOVE_MEETING_SUCCESS';
export const REMOVE_MEETING_FAILURE = 'REMOVE_MEETING_FAILURE';

// MENTEES

export const GET_MENTEES_START = 'GET_MENTEES_START';
export const GET_MENTEES_SUCCESS = 'GET_MENTEES_SUCCESS';
export const GET_MENTEES_FAILURE = 'GET_MENTEES_FAILURE';

export const GET_SPECIFIC_MENTEE_START = 'GET_SPECIFIC_MENTEE_START';
export const GET_SPECIFIC_MENTEE_SUCCESS = 'GET_SPECIFIC_MENTEE_SUCCESS';
export const GET_SPECIFIC_MENTEE_FAILURE = 'GET_SPECIFIC_MENTEE_FAILURE';

export const CREATE_MENTEE_START = 'CREATE_MENTEE_START';
export const CREATE_MENTEE_SUCCESS = 'CREATE_MENTEE_SUCCESS';
export const CREATE_MENTEE_FAILURE = 'CREATE_MENTEE_FAILURE';

export const UPDATE_MENTEE_START = 'UPDATE_MENTEE_START';
export const UPDATE_MENTEE_SUCCESS = 'UPDATE_MENTEE_SUCCESS';
export const UPDATE_MENTEE_FAILURE = 'UPDATE_MENTEE_FAILURE';

export const DELETE_MENTEE_START = 'DELETE_MENTEE_START';
export const DELETE_MENTEE_SUCCESS = 'DELETE_MENTEE_SUCCESS';
export const DELETE_MENTEE_FAILURE = 'DELETE_MENTEE_FAILURE';

export const REMOVE_MENTEE_START = 'REMOVE_MENTEE_START';
export const REMOVE_MENTEE_SUCCESS = 'REMOVE_MENTEE_SUCCESS';
export const REMOVE_MENTEE_FAILURE = 'REMOVE_MENTEE_FAILURE';

// MENTORS

export const GET_MENTORS_START = 'GET_MENTORS_START';
export const GET_MENTORS_SUCCESS = 'GET_MENTORS_SUCCESS';
export const GET_MENTORS_FAILURE = 'GET_MENTORS_FAILURE';

export const GET_SPECIFIC_MENTOR_START = 'GET_SPECIFIC_MENTOR_START';
export const GET_SPECIFIC_MENTOR_SUCCESS = 'GET_SPECIFIC_MENTOR_SUCCESS';
export const GET_SPECIFIC_MENTOR_FAILURE = 'GET_SPECIFIC_MENTOR_FAILURE';

export const CREATE_MENTOR_START = 'CREATE_MENTOR_START';
export const CREATE_MENTOR_SUCCESS = 'CREATE_MENTOR_SUCCESS';
export const CREATE_MENTOR_FAILURE = 'CREATE_MENTOR_FAILURE';

export const UPDATE_MENTOR_START = 'UPDATE_MENTOR_START';
export const UPDATE_MENTOR_SUCCESS = 'UPDATE_MENTOR_SUCCESS';
export const UPDATE_MENTOR_FAILURE = 'UPDATE_MENTOR_FAILURE';

export const DELETE_MENTOR_START = 'DELETE_MENTOR_START';
export const DELETE_MENTOR_SUCCESS = 'DELETE_MENTOR_SUCCESS';
export const DELETE_MENTOR_FAILURE = 'DELETE_MENTOR_FAILURE';

export const REMOVE_MENTOR_START = 'REMOVE_MENTOR_START';
export const REMOVE_MENTOR_SUCCESS = 'REMOVE_MENTOR_SUCCESS';
export const REMOVE_MENTOR_FAILURE = 'REMOVE_MENTOR_FAILURE';

// NOTIFICATIONS

export const GET_NOTIFICATIONS_START = 'GET_NOTIFICATIONS_START';
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_FAILURE = 'GET_NOTIFICATIONS_FAILURE';

export const GET_SPECIFIC_NOTIFICATION_START = 'GET_SPECIFIC_NOTIFICATION_START';
export const GET_SPECIFIC_NOTIFICATION_SUCCESS = 'GET_SPECIFIC_NOTIFICATION_SUCCESS';
export const GET_SPECIFIC_NOTIFICATION_FAILURE = 'GET_SPECIFIC_NOTIFICATION_FAILURE';

export const CREATE_NOTIFICATION_START = 'CREATE_NOTIFICATION_START';
export const CREATE_NOTIFICATION_SUCCESS = 'CREATE_NOTIFICATION_SUCCESS';
export const CREATE_NOTIFICATION_FAILURE = 'CREATE_NOTIFICATION_FAILURE';

export const UPDATE_NOTIFICATION_START = 'UPDATE_NOTIFICATION_START';
export const UPDATE_NOTIFICATION_SUCCESS = 'UPDATE_NOTIFICATION_SUCCESS';
export const UPDATE_NOTIFICATION_FAILURE = 'UPDATE_NOTIFICATION_FAILURE';

export const MARK_NOTIFICATION_START = 'MARK_NOTIFICATION_START';
export const MARK_NOTIFICATION_SUCCESS = 'MARK_NOTIFICATION_SUCCESS';
export const MARK_NOTIFICATION_FAILURE = 'MARK_NOTIFICATION_FAILURE';

export const DELETE_NOTIFICATION_START = 'DELETE_NOTIFICATION_START';
export const DELETE_NOTIFICATION_SUCCESS = 'DELETE_NOTIFICATION_SUCCESS';
export const DELETE_NOTIFICATION_FAILURE = 'DELETE_NOTIFICATION_FAILURE';

export const REMOVE_NOTIFICATION_START = 'REMOVE_NOTIFICATION_START';
export const REMOVE_NOTIFICATION_SUCCESS = 'REMOVE_NOTIFICATION_SUCCESS';
export const REMOVE_NOTIFICATION_FAILURE = 'REMOVE_NOTIFICATION_FAILURE';

// ORGANIZATIONS

export const GET_ORGANIZATIONS_START = 'GET_ORGANIZATIONS_START';
export const GET_ORGANIZATIONS_SUCCESS = 'GET_ORGANIZATIONS_SUCCESS';
export const GET_ORGANIZATIONS_FAILURE = 'GET_ORGANIZATIONS_FAILURE';

export const GET_SPECIFIC_ORGANIZATION_START = 'GET_SPECIFIC_ORGANIZATION_START';
export const GET_SPECIFIC_ORGANIZATION_SUCCESS = 'GET_SPECIFIC_ORGANIZATION_SUCCESS';
export const GET_SPECIFIC_ORGANIZATION_FAILURE = 'GET_SPECIFIC_ORGANIZATION_FAILURE';

export const UPDATE_ORGANIZATION_START = 'UPDATE_ORGANIZATION_START';
export const UPDATE_ORGANIZATION_SUCCESS = 'UPDATE_ORGANIZATION_SUCCESS';
export const UPDATE_ORGANIZATION_FAILURE = 'UPDATE_ORGANIZATION_FAILURE';

export const DELETE_ORGANIZATION_START = 'DELETE_ORGANIZATION_START';
export const DELETE_ORGANIZATION_SUCCESS = 'DELETE_ORGANIZATION_SUCCESS';
export const DELETE_ORGANIZATION_FAILURE = 'DELETE_ORGANIZATION_FAILURE';

export const REMOVE_ORGANIZATION_START = 'REMOVE_ORGANIZATION_START';
export const REMOVE_ORGANIZATION_SUCCESS = 'REMOVE_ORGANIZATION_SUCCESS';
export const REMOVE_ORGANIZATION_FAILURE = 'REMOVE_ORGANIZATION_FAILURE';

// USERS

export const GET_USERS_START = 'GET_USERS_START';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

export const GET_SPECIFIC_USER_START = 'GET_SPECIFIC_USER_START';
export const GET_SPECIFIC_USER_SUCCESS = 'GET_SPECIFIC_USER_SUCCESS';
export const GET_SPECIFIC_USER_FAILURE = 'GET_SPECIFIC_USER_FAILURE';

export const GET_CURRENT_USER_START = 'GET_CURRENT_USER_START';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';
export const GET_CURRENT_USER_FAILURE = 'GET_CURRENT_USER_FAILURE';

export const UPDATE_USER_START = 'UPDATE_USER_START';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const DELETE_USER_START = 'DELETE_USER_START';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

export const REMOVE_USER_START = 'REMOVE_USER_START';
export const REMOVE_USER_SUCCESS = 'REMOVE_USER_SUCCESS';
export const REMOVE_USER_FAILURE = 'REMOVE_USER_FAILURE';
