import {
    GET_INVITATIONS_START,
    GET_INVITATIONS_SUCCESS,
    GET_INVITATIONS_FAILURE,
    GET_SPECIFIC_INVITATION_START,
    GET_SPECIFIC_INVITATION_SUCCESS,
    GET_SPECIFIC_INVITATION_FAILURE,
    CREATE_INVITATION_START,
    CREATE_INVITATION_SUCCESS,
    CREATE_INVITATION_FAILURE,
    UPDATE_INVITATION_START,
    UPDATE_INVITATION_SUCCESS,
    UPDATE_INVITATION_FAILURE,
    DELETE_INVITATION_START,
    DELETE_INVITATION_SUCCESS,
    DELETE_INVITATION_FAILURE,
    REMOVE_INVITATION_START,
    REMOVE_INVITATION_SUCCESS,
    REMOVE_INVITATION_FAILURE
} from '../constants/actionTypes';

const initialState = {
    
}

export default (state = initialState, action) => {
    switch(action.type){
        default:
            return state;
    }
}